# Generated by Django 5.1.4 on 2024-12-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_supplier_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
