# Generated by Django 5.1.4 on 2024-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ProductImage_path',
        ),
        migrations.AddField(
            model_name='item',
            name='ProductImage',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images/'),
        ),
    ]
