# Generated by Django 5.1.4 on 2024-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ProductImage',
            field=models.ImageField(default='default_image.jpg', upload_to='product/'),
        ),
    ]
