# Generated by Django 5.1.4 on 2024-12-16 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_category_supplier_alter_item_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField(blank=True, db_column='CustomerID', null=True)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('subtotal', models.IntegerField(blank=True, db_column='subtotal', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('auth_user', models.ForeignKey(blank=True, db_column='auth_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(blank=True, db_column='Item', to='shop.item')),
            ],
        ),
    ]
